---
title: "dataAnalysis"
output: html_document
---
# Jason Ryan May


# My data analysis portion of the project.

## Question: Can we predict the storm event type from these features? 

```{r}
library(tidyverse)
```


```{r}
dat <- read_csv("mergedData_2023.csv")
glimpse(dat)
```

```{r}
# drop columns that are demographic related or redundant
dat <- dat |>
  select(-STATE, -CZ_NAME, -MONTH_NAME)

# split the fips column into two columns, one for state fips (the first two characters) and one for county fips (the last three characters)
dat <- dat |>
  mutate(FIPS = as.numeric(FIPS)) |>
  separate(FIPS, into = c("state_fips", "county_fips"), sep = 2)

# hot swap all categorical variables except event type to numeric factors
dat <- dat |>
  mutate(
    COASTAL_TYPE_SHORELINE = as.numeric(as.factor(COASTAL_TYPE_SHORELINE)),
    COASTAL_TYPE_WATERSHED = as.numeric(as.factor(COASTAL_TYPE_WATERSHED)),
    MODAL_YEAR_BUILT_BIN   = as.numeric(as.factor(MODAL_YEAR_BUILT_BIN)),
    state_fips = as.numeric(as.factor(state_fips)),
    county_fips = as.numeric(as.factor(county_fips)),
    )


# drop zero storm area and zero duration
# dat <- dat |>
  # filter(STORM_AREA_SQMILES > 0, DURATION_MINUTES > 0)
  # select(-STORM_AREA_SQMILES, -DURATION_MINUTES)

# fill missing damage with the median
dat <- dat |>
  mutate(DAMAGE_PROPERTY = ifelse(is.na(DAMAGE_PROPERTY), median(DAMAGE_PROPERTY, na.rm = TRUE), DAMAGE_PROPERTY))

# drop missing
dat <- dat |>
  drop_na()

glimpse(dat)

# download the dat as cleanedData.csv
write_csv(dat, "cleanedData.csv")


# scale the data 
dat_scaled <- dat |>
  select(-EVENT_TYPE) |> ## Remove EVENT TYPE column (not used for scaling)
  data.matrix() |>
  scale() |>
  as_tibble() |>
  mutate(EVENT_TYPE = dat$EVENT_TYPE) ## Add back the EVENT_TYPE column for later use
```

```{r}
# perform pca on the data, excluding the event type column the first column

p <- dat |>
select(-EVENT_TYPE) |> ## Remove EVENT TYPE column (not used for PCA)
data.matrix() |>
prcomp(scale = TRUE)

# plot the pca scores
plot(p)

p$x |>
as_tibble() |>
select(PC2, PC1) |>
mutate(EVENT_TYPE = dat$EVENT_TYPE ) |>
ggplot(aes(PC1, PC2)) +
geom_point(aes(color = EVENT_TYPE))

```

```{r}
library(tidymodels)

kresult <- kmeans(p$x, centers = 5)

tidy(kresult)

augment(kresult, p$x)


augment(kresult, p$x) |>
ggplot(aes(PC1,PC2)) +
geom_jitter(aes(color = .cluster),
width = 0.2, height = 0.2,
size = 3)

```






